Repository newrelic/infrastructure-agent, pull requests merged in 2020-08, with the labels that each got.

#61 ci: adding code coverage steps to send data to coveralls.io
  .github/workflows/test.yml
  .gitignore
  build/infra_build.mk
Labels: ready for review

#60 feat: Dimensional Metrics (DM) entities are now registered with identity endpoint
  cmd/newrelic-infra/newrelic-infra.go
  go.sum
  internal/agent/agent.go
  internal/agent/agent_test.go
  internal/agent/id_provider.go
  internal/agent/id_provider_test.go
  internal/agent/mocks/AgentContext.go
  internal/agent/register_service.go
  internal/agent/register_service_test.go
  internal/plugins/testing/agent_mock.go
  pkg/backend/identityapi/api_client.go
  pkg/backend/identityapi/connect_client.go
  pkg/backend/identityapi/register_client.go
  pkg/backend/identityapi/register_client_test.go
  pkg/config/defaults.go
  pkg/identity-client/client.go
  pkg/integrations/legacy/runner_test.go
  pkg/integrations/v4/dm/emitter.go
  pkg/integrations/v4/dm/emitter_test.go
  pkg/integrations/v4/dm/processor.go
  pkg/integrations/v4/emitter/emitter.go
  pkg/integrations/v4/emitter/emitter_test.go
  pkg/integrations/v4/emitter/emitter_v4.go
  pkg/metrics/process/sampler_linux_test.go
  pkg/metrics/procs_windows_test.go
  pkg/metrics/storage/storage_sampler_test.go
  test/fixture/integration/protocol_v4.go
  test/fuzz/integration_payload/corpus/v4Payload.json
  test/fuzz/integration_payload/corpus/v4Payload_one_line.json
  test/fuzz/integration_payload/fuzz.go
  test/infra/agent.go
Labels: ready for review

#64 Add an infra-agent configuration template
  assets/examples/infrastructure/newrelic-infra-template.yml.example
Labels: documentation, ready for review

#63 fix: fixed race condition accessing agentKey in agent ctx
  internal/agent/agent.go
  internal/agent/event_sender_test.go
  internal/agent/event_sender_vortex_test.go
  internal/agent/patch_sender_test.go
  pkg/ctl/sender/client_docker_test.go
  pkg/ctl/shutdown_linux_test.go
Labels: bug, ready for review

#62 chore: upgraded Docker client to v19.03.12
  go.mod
  go.sum
  pkg/ctl/sender/client_docker.go
  pkg/databind/internal/discovery/docker/docker.go
  pkg/helpers/docker_utils.go
Labels: ready for review

#59 Fix deltas order race submission condition for remote entities
  internal/agent/bulk_inventories_test.go
  internal/agent/delta/plugins.go
  internal/agent/delta/store.go
  internal/agent/delta/store_test.go
  internal/agent/patch_sender_test.go
  pkg/backend/inventoryapi/ingestapi_types.go
  test/core/core.go
  test/core/deltas_test.go
Labels: bug, ready for review

#70 Allocate inventory queue
  internal/agent/agent.go
  pkg/config/config.go
  pkg/config/defaults.go
Labels: enhancement, ready for review

#71 Feature flag support for: non blocking inventory processing queue
  internal/agent/agent.go
  internal/agent/cmdchannel/handler/featureflag_handler.go
  internal/agent/cmdchannel/service_test.go
  pkg/config/config.go
  pkg/config/defaults.go
  pkg/trace/features.go
Labels: ready for review

#72 feat: moved back to using original telemetry SDK and adding rate and cumulative rate into the agent
  go.mod
  go.sum
  pkg/integrations/v4/dm/rate/calculator.go
  pkg/integrations/v4/dm/rate/calculator_test.go
  pkg/integrations/v4/dm/sender.go
  pkg/integrations/v4/dm/sender_test.go
  pkg/integrations/v4/dm/telemetry.go
Labels: ready for review

#73 Edit to OSS files and README
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/troubleshooting.md
  .github/pull_request_template.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  README.md
Labels: documentation

#75 fix/last submission time on save
  internal/agent/id_provider_test.go
  internal/agent/patch_sender.go
  internal/agent/patch_sender_test.go
  internal/agent/plugin.go
  internal/plugins/linux/daemontools_test.go
  internal/plugins/linux/facter.go
  internal/plugins/linux/selinux_test.go
  internal/plugins/linux/sysctl_polling.go
  internal/plugins/linux/upstart.go
  pkg/plugins/agent_config.go
Labels: ready for review

#66 feat: register entities - id lookup
  cmd/newrelic-infra/newrelic-infra.go
  pkg/backend/identityapi/register_client.go
  pkg/integrations/v4/dm/emitter.go
  pkg/integrations/v4/dm/emitter_test.go
  pkg/integrations/v4/dm/id_provider.go
  pkg/integrations/v4/dm/id_provider_test.go
Labels: ready for review

#77 Feat/winlog filtering support
  pkg/integrations/v4/logs/cfg.go
  pkg/integrations/v4/logs/cfg_template.go
  pkg/integrations/v4/logs/cfg_test.go
Labels: ready for review

#84 [LOGGING-3157] modify Message and EventType
  pkg/integrations/v4/logs/cfg.go
  pkg/integrations/v4/logs/cfg_template.go
  pkg/integrations/v4/logs/cfg_test.go
Labels: ready for review

#78 chore: upgraded fsnotify to v1.4.9
  go.mod
  go.sum
  internal/agent/bulk_inventories_test.go
  internal/agent/delta/store.go
  internal/agent/delta/store_test.go
  internal/plugins/linux/dpkg.go
  internal/plugins/linux/rpm.go
  internal/plugins/linux/sysctl_subscriber.go
  internal/plugins/linux/users.go
  pkg/integrations/v4/logs/cfg_watcher.go
  pkg/integrations/v4/manager.go
  pkg/plugins/files_config.go
  test/harvest/sysctl_test.go
Labels: ready for review
