Repository newrelic/infrastructure-agent, pull requests merged in 2021-06, with the labels that each got.

#489 fix: hash collision on cache and integration tests
  .gitignore
  build/build.mk
  build/windows/test.ps1
  internal/integrations/v4/cache/cache.go
  internal/integrations/v4/cache/cache_test.go
  internal/integrations/v4/integration/definition.go
  internal/integrations/v4/integration/integration.go
  internal/integrations/v4/runner/runner.go
  internal/integrations/v4/runner/runner_test.go
  pkg/integrations/configrequest/handler.go
  pkg/integrations/configrequest/handler_test.go
  pkg/integrations/configrequest/protocol/protocol.go
  pkg/integrations/configrequest/protocol/v1.go
  test/cfgprotocol/agent/emulator.go
  test/cfgprotocol/cfgprotocol_test.go
  test/cfgprotocol/helper.go
  test/cfgprotocol/testdata/go/spawner.go
  test/cfgprotocol/testdata/scenarios/scenario0/nri-config.json
  test/cfgprotocol/testdata/scenarios/scenario0/settings.yml
  test/cfgprotocol/testdata/scenarios/scenario1/nri-config.json
  test/cfgprotocol/testdata/scenarios/scenario1/settings.yml
  test/cfgprotocol/testdata/scenarios/scenario2/settings.yml
  test/cfgprotocol/testdata/scenarios/scenario3/settings.yml
  test/cfgprotocol/testdata/scenarios/scenario4/nri-config.txt
  test/cfgprotocol/testdata/scenarios/shared/nri-out.json
  test/cfgprotocol/testdata/scenarios/shared/nri-out.v4.json
  test/cfgprotocol/testdata/scenarios/v4_payload/nri-config.json
  test/cfgprotocol/testdata/scenarios/v4_payload/settings.yml
  test/cfgprotocol/testdata/templates/nri-config-integration-short.json
  test/cfgprotocol/testdata/templates/nri-config-two-integrations.json
  test/cfgprotocol/testdata/templates/nri-config.json
  test/cfgprotocol/testdata/templates/settings.yml
  test/infra/agent.go
Labels: ready for review

#475 [0.5d] Status endpoint
  cmd/newrelic-infra/newrelic-infra.go
  internal/agent/agent.go
  internal/agent/agent_test.go
  internal/agent/status/status.go
  internal/agent/status/status_test.go
  internal/statusapi/statusapi.go
  internal/statusapi/statusapi_test.go
  pkg/backend/http/http_client.go
  pkg/config/config.go
  pkg/config/defaults.go
  pkg/integrations/v4/dm/sender.go
  pkg/integrations/v4/dm/sender_test.go
Labels: ready for review

#503 test: ansible playbook to run harvest tests on all supported OSs
  .gitignore
  build/build.mk
  test/harvest/ansible/inventory.sample
  test/harvest/ansible/roles/build-harvest-tests/tasks/main.yml
  test/harvest/ansible/roles/build-harvest-tests/vars/main.yml
  test/harvest/ansible/roles/run-harvest-tests/tasks/main.yml
  test/harvest/ansible/roles/run-harvest-tests/vars/main.yml
  test/harvest/ansible/test.sh
  test/harvest/ansible/test.yml
Labels: epic/new-mem-metrics, ready for review

#477 Agent self instrumentation through prometheus exporter
  cmd/newrelic-infra/newrelic-infra.go
  go.mod
  go.sum
  internal/instrumentation/exporter.go
  internal/instrumentation/exporter_test.go
  internal/instrumentation/instrumentation.go
  internal/instrumentation/noop.go
  internal/instrumentation/noop_test.go
  internal/instrumentation/prometheus_integration_conf.go
  internal/instrumentation/prometheus_integration_conf_test.go
  pkg/config/config.go
  pkg/entity/register/worker.go
  pkg/entity/register/worker_test.go
  pkg/integrations/v4/dm/emitter.go
  pkg/integrations/v4/dm/emitter_test.go
  pkg/log/exported.go
  pkg/log/log.go
  test/cfgprotocol/agent/emulator.go
Labels: ready for review

#513 Ci/provision machines for tests
  .gitignore
  build/build.mk
  test/harvest/ansible/README.md
  test/harvest/ansible/automated-test.sh
  test/harvest/ansible/group_vars/localhost/main.yml
  test/harvest/ansible/inventory.local
  test/harvest/ansible/provision-ec2.yml
  test/harvest/ansible/roles/add-ssh-keys/tasks/main.yml
  test/harvest/ansible/roles/install-python/tasks/main.yml
  test/harvest/ansible/roles/install-python/vars/main.yml
  test/harvest/ansible/roles/provision-ec2/tasks/main.yml
  test/harvest/ansible/roles/provision-ec2/templates/inventory.ec2.j2
  test/harvest/ansible/roles/provision-ec2/vars/main.yml
  test/harvest/ansible/roles/run-harvest-tests/tasks/main.yml
  test/harvest/ansible/roles/run-harvest-tests/vars/main.yml
  test/harvest/ansible/roles/terminate-ec2/tasks/main.yml
  test/harvest/ansible/terminate-ec2.yml
  test/harvest/ansible/test.sh
  test/harvest/ansible/test.yml
Labels: ready for review

#527 Stop service on daemon error without triggering os:Exit
  cmd/newrelic-infra-service/newrelic-infra-service.go
  internal/agent/service/service.go
  internal/agent/service/service_unix.go
  internal/agent/service/service_windows.go
Labels: do-not-merge, enhancement

#542 docs: status API
  docs/status_api.md
Labels: ready for review

#541 fix: flaky test - time race
  internal/statusapi/statusapi_test.go
Labels: ready for review

#533 feat: changed location from where the agent executes fluent-bit
  pkg/config/config.go
  pkg/config/config_linux.go
  pkg/config/config_windows.go
  pkg/config/defaults.go
  pkg/integrations/v4/logs/loader_test.go
Labels: epic/package-log-fwd

#524 Stop service with daemon child exit code
  cmd/newrelic-infra-service/newrelic-infra-service.go
  internal/agent/service/service.go
  internal/agent/service/service_unix.go
  internal/agent/service/service_windows.go
  internal/os/api/exit_code.go
  internal/statusapi/statusapi_test.go
Labels: Ready for: review

#523 ci: fluentbit as agent pkg dependency
  .github/workflows/prerelease_linux.yml
  .github/workflows/prerelease_staged_publish.yml
  .github/workflows/release.yml
  .github/workflows/release_staged.yml
  build/.goreleaser.yml
  build/embed/fluent-bit.mk
  build/embed/fluent-bit.version
  build/upload-schema-linux-rpm.yml
Labels: Ready for: review, epic/package-log-fwd

#563 fix: fixed typo in prerelease publish action tag
  .github/workflows/prerelease_linux.yml
  build/embed/fluent-bit.version
Labels: Ready for: review, epic/package-log-fwd

#560 feat: added recovery policy for windows service
  build/package/windows/newrelic-infra-386-installer/newrelic-infra/Product.wxs
  build/package/windows/newrelic-infra-386-installer/newrelic-infra/newrelic-infra-installer.wixproj
  build/package/windows/newrelic-infra-amd64-installer/newrelic-infra/Product.wxs
  build/package/windows/newrelic-infra-amd64-installer/newrelic-infra/newrelic-infra-installer.wixproj
  internal/agent/service/service.go
Labels: Ready for: review

#550 test: update tests for logging feature
  pkg/config/config.go
  test/packaging/ansible/roles/logging/tasks/main.yaml
  test/packaging/ansible/roles/package-files-verification/vars/package-files-Amazon-2-aarch64.yaml
  test/packaging/ansible/roles/package-files-verification/vars/package-files-Redhat-7.yaml
  test/packaging/ansible/roles/package-files-verification/vars/package-files-Redhat-8.yaml
  test/packaging/ansible/roles/package-files-verification/vars/package-files-SLES-12.3.yaml
  test/packaging/ansible/roles/package-files-verification/vars/package-files-Ubuntu-16.yaml
  test/packaging/ansible/roles/package-files-verification/vars/package-files-Ubuntu-18.yaml
  test/packaging/ansible/roles/package-files-verification/vars/package-files-Ubuntu-20.yaml
Labels: Ready for: review

#552 ci: update goreleaser to version 0.169.0
  build/release.mk
Labels: Ready for: review

#212 HostType fix
  internal/plugins/linux/hostinfo.go
  internal/plugins/windows/hostinfo.go
Labels: Ready for: review

#562 Package log forwarder
  .github/workflows/prerelease_linux.yml
  .github/workflows/prerelease_staged_publish.yml
  .github/workflows/release.yml
  .github/workflows/release_staged.yml
  build/.goreleaser.yml
  build/embed/fluent-bit.mk
  build/embed/fluent-bit.version
  build/upload-schema-linux-rpm.yml
  pkg/config/config.go
  pkg/config/config_linux.go
  pkg/config/config_windows.go
  pkg/config/defaults.go
  pkg/integrations/v4/logs/loader_test.go
  test/packaging/ansible/roles/logging/tasks/main.yaml
  test/packaging/ansible/roles/package-files-verification/vars/package-files-Amazon-2-aarch64.yaml
  test/packaging/ansible/roles/package-files-verification/vars/package-files-Redhat-7.yaml
  test/packaging/ansible/roles/package-files-verification/vars/package-files-Redhat-8.yaml
  test/packaging/ansible/roles/package-files-verification/vars/package-files-SLES-12.3.yaml
  test/packaging/ansible/roles/package-files-verification/vars/package-files-Ubuntu-16.yaml
  test/packaging/ansible/roles/package-files-verification/vars/package-files-Ubuntu-18.yaml
  test/packaging/ansible/roles/package-files-verification/vars/package-files-Ubuntu-20.yaml
Labels: epic/package-log-fwd

#596 feat: structure traces feature into proper field
  pkg/metrics/sampler/matcher_test.go
  pkg/trace/trace.go
Labels: enhancement
